### ISSUE TITLE
Pinterest Android App: Sharing via Intent.ACTION_SEND crashes com.pinterest.activity.create.PinItActivity

### ISSUE THREAD

**Issue by siegfriedpammer** [pinterest/android-pdk#24]
I am aware of the fact that this bug does not relate to the android-pdk, but please read on instead of closing immediately:

I am posting this here because I have not found a bugtracker for the pinterest android app. Can somebody redirect me to the "official" bugtracker or report form? I looked around pinterest.com and developers.pinterest.com but it seems there's no way to report a bug affecting the android app.

Thank you very much!

My code is as follows:

		@Override
		public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
			ResolveInfo launchable = possibleTargets.get(position);
			ActivityInfo activity = launchable.activityInfo;

			ComponentName name = new ComponentName(activity.applicationInfo.packageName, activity.name);

			Intent sendIntent = createSendIntent(quote, shareType);
			Uri fileUri = sendIntent.getParcelableExtra(Intent.EXTRA_TEXT);
			sendIntent.setComponent(name);
			sendIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
			if (fileUri != null) {
				getContext().grantUriPermission(activity.applicationInfo.packageName, fileUri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
			}
			getContext().startActivity(sendIntent);
		}

		private Intent createSendIntent(Quote quote, int shareType) {
			Intent actionSendIntent = new Intent(Intent.ACTION_SEND);
			actionSendIntent.putExtra(Intent.EXTRA_SUBJECT, getContext().getResources().getString(R.string.app_name));

			switch (shareType) {
				case ShareTools.SHARE_TYPE_TEXT:
					actionSendIntent.setType("text/plain");
					actionSendIntent.putExtra(Intent.EXTRA_TEXT, quote.text + " - " + quote.author);
					break;
				case ShareTools.SHARE_TYPE_PICTURE:
					try {
						Uri content = ShareTools.getUriForQuoteImage(getContext(), quote);
						actionSendIntent.putExtra(Intent.EXTRA_STREAM, content);
						actionSendIntent.setDataAndType(content, "image/jpeg");
					} catch (IOException ex) {
						Toast.makeText(getContext(), ex.getMessage(), Toast.LENGTH_LONG).show();
						ex.printStackTrace();
					}
					break;
			}

			return actionSendIntent;
		}

`ShareTools.getUriForQuoteImage` generates the image (stream) and makes it publicly available via a file provider, this works fine with other apps such as Skype, WhatsApp, KakaoTalk and so on, thus should not be a problem.

I get the following exception after starting activity `com.pinterest.activity.create.PinItActivity`

	E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pinterest/com.pinterest.activity.create.PinItActivity}: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
		at android.app.ActivityThread.access$700(ActivityThread.java:159)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
		at android.os.Handler.dispatchMessage(Handler.java:99)
		at android.os.Looper.loop(Looper.java:176)
		at android.app.ActivityThread.main(ActivityThread.java:5419)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:525)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
		at dalvik.system.NativeStart.main(Native Method)
	Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
		at android.database.CursorWindow.nativeGetLong(Native Method)
		at android.database.CursorWindow.getLong(CursorWindow.java:511)
		at android.database.CursorWindow.getInt(CursorWindow.java:578)
		at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
		at android.database.CursorWrapper.getInt(CursorWrapper.java:102)
		at com.pinterest.common.kit.utils.ImageUtils.getRotationForImage(SourceFile:234)
		at com.pinterest.common.kit.utils.ImageUtils.rotateBitmapIfNeeded(SourceFile:202)
		at com.pinterest.common.kit.utils.ImageUtils.imageFromUri(SourceFile:146)
		at com.pinterest.activity.create.fragment.CreateBaseFragment.setImageUri(SourceFile:595)
		at com.pinterest.activity.create.fragment.CreateBaseFragment.init(SourceFile:322)
		at com.pinterest.activity.create.fragment.CreateBaseFragment.onCreateView(SourceFile:118)
		at android.support.v4.app.Fragment.performCreateView(SourceFile:1974)
		at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1067)
		at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1252)
		at android.support.v4.app.BackStackRecord.run(SourceFile:742)
		at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:1617)
		at android.support.v4.app.FragmentController.execPendingActions(SourceFile:339)
		at android.support.v4.app.FragmentActivity.onStart(SourceFile:602)
		at com.pinterest.kit.activity.SocialConnectActivity.onStart(SourceFile:112)
		at com.pinterest.kit.activity.BaseActivity.onStart(SourceFile:96)
		at com.pinterest.activity.create.PinItActivity.onStart(SourceFile:66)
		at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
		at android.app.Activity.performStart(Activity.java:5382)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) 
		at android.app.ActivityThread.access$700(ActivityThread.java:159) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
		at android.os.Handler.dispatchMessage(Handler.java:99) 
		at android.os.Looper.loop(Looper.java:176) 
		at android.app.ActivityThread.main(ActivityThread.java:5419) 
		at java.lang.reflect.Method.invokeNative(Native Method) 
		at java.lang.reflect.Method.invoke(Method.java:525) 
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) 
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) 
		at dalvik.system.NativeStart.main(Native Method)

**Comment by siegfriedpammer** [comment]
solved by: http://stackoverflow.com/questions/37479267/share-to-pinterest-doesnt-work-on-marshmallow
