### ISSUE TITLE
PDK login leads to crash the Pinterest app when not logged in app.

### ISSUE THREAD

**Issue by vigneshwaran-ms** [pinterest/android-pdk#37]
When using pdk sdk to login and the user did not logged in the app the redirection leads to crash. below is the crash log.
`                                                --------- beginning of crash
06-16 19:13:43.313 7237-7237/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.pinterest, PID: 7237
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pinterest/com.pinterest.sdk.PinterestOauthActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.CookieStore java.net.CookieManager.getCookieStore()' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.CookieStore java.net.CookieManager.getCookieStore()' on a null object reference
                                                     at com.pinterest.kit.h.w.c(SourceFile:166)
                                                     at com.pinterest.sdk.PinterestOauthActivity.onCreate(SourceFile:1109)
                                                     at android.app.Activity.performCreate(Activity.java:6251)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

**Comment by Zehhu** [comment]
Thanks I'll look at this

**Comment by rafamartins** [comment]
Same issue here.

**Comment by KaluKhan** [comment]
I am facing same issue. Please any update about this issue...

**Comment by ABBIGADDU** [comment]
i am also facing the same issue . Please any update about this issue....

**Comment by motis10** [comment]
I am facing same issue!!!!

**Comment by Zehhu** [comment]
Sorry for the slow update. One of our engineers just fixed this today, it should go out in the next release.

**Comment by ABBIGADDU** [comment]
know not at i am still getting crashes ...

**Comment by Zehhu** [comment]
The release isn't out yet and will take a few weeks before users will get it.

**Comment by christinalee** [comment]
To clarify, the fix went into the next version of the Pinterest Android app, version 6.36. Any users on that version of the app or newer should no longer see this crash. Users who do not upgrade the Pinterest app will continue to see the crash.
