### ISSUE TITLE
Pinterest app getting crash.

### ISSUE THREAD

**Issue by RajeshkumarA-Contus** [pinterest/android-pdk#43]
Pinterest application getting crash when using pdk with login.

**Comment by motis10** [comment]
java.lang.IllegalArgumentException: String is too long, truncating to 100 characters
                                                at com.crashlytics.android.a.d.a(SourceFile:38)
                                                at com.crashlytics.android.a.c.a(SourceFile:1038)
                                                at com.pinterest.f.f.a.a(SourceFile:413)
                                                at com.pinterest.f.f.a.c(SourceFile:5385)
                                                at com.pinterest.f.f.a$a.uncaughtException(SourceFile:95)
                                                at com.crashlytics.android.c.n.uncaughtException(SourceFile:38)
                                                at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
09-11 18:27:48.090 11779-11779/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.pinterest, PID: 11779
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pinterest/com.pinterest.sdk.PinterestOauthActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.CookieStore java.net.CookieManager.getCookieStore()' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:178)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                       at android.os.Looper.loop(Looper.java:194)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.CookieStore java.net.CookieManager.getCookieStore()' on a null object reference
                                                       at com.pinterest.kit.h.w.c(SourceFile:166)
                                                       at com.pinterest.sdk.PinterestOauthActivity.onCreate(SourceFile:1109)
                                                       at android.app.Activity.performCreate(Activity.java:6092)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:178) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                       at android.os.Looper.loop(Looper.java:194) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5637) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by Zehhu** [comment]
Related to https://github.com/pinterest/android-pdk/issues/37
